# Generated by Django 3.2.16 on 2022-10-06 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark_sentence', to=settings.AUTH_USER_MODEL),
        ),
    ]
